In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from PIL import Image

In [2]:
# Load and preprocess data
train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
    'data/Training',
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical')

Found 2870 images belonging to 4 classes.


In [14]:
print(len(train_generator))

90


In [4]:
# Get a batch of images and labels
images, labels = train_generator[0]

# Get the first image and label from the batch
first_image = images[0]
first_label = labels[0]

# Convert the image array to a Pillow Image
first_image = Image.fromarray((first_image * 255).astype('uint8'))

# Show the image
#first_image.show()

# Print the label
print(f'Label: {first_label}')


Label: [0. 1. 0. 0.]


In [7]:
# Get the shape of the images
image_shape = train_generator.image_shape
print(f'Image Shape: {image_shape}')

# Get the number of batches per epoch
num_batches = len(train_generator)
print(f'Number of Batches per Epoch: {num_batches}')

# Get the total number of samples
num_samples = train_generator.n
print(f'Total Number of Samples: {num_samples}')

# Get the batch size
batch_size = train_generator.batch_size
print(f'Batch Size: {batch_size}')

Image Shape: (150, 150, 3)
Number of Batches per Epoch: 90
Total Number of Samples: 2870
Batch Size: 32


In [13]:
sample_image = images[10]
print(sample_image)

[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.00784314 0.00784314 0.00784314]
  [0.00784314 0.00784314 0.00784314]
  [0.00784314 0.00784314 0.00784314]]

 [[0.00392157 0.00392157 0.00392157]
  [0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  ...
  [0.01176471 0.01176471 0.01176471]
  [0.01568628 0.01568628 0.01568628]
  [0.00784314 0.00784314 0.00784314]]

 ...

 [[0.00784314 0.00784314 0.00784314]
  [0.00784314 0.00784314 0.00784314]
  [0.01176471 0.01176471 0.01176471]
  ...
  [0.01568628 0.01568628 0.01568628]
  [0.01176471 0.01176471 0.01176471]
  [0.00784314 0.00784314 0.00784314]]

 [[0.00784314 0.00784314 0.00784314]
  [0.00784314 0.00784314 0.00784314]
